### ISSUE TITLE
Consider creating releases

### ISSUE THREAD

**Issue by sidiabale** [Pmovil/CN1WindowsPort#13]
Hi,

I see that there are no releases for this project. I know this is work in progress but even at that, I think it would help to have releases with descriptions of what the contain, etc. so that users can a reference of what they're integrating. 

What do you think?

**Comment by FabricioCabeca** [comment]
You are right, the point is that I've been too busy to write down everything we did and a better how-to. My current focus now is creating the offline build tools using the new VM, it should ease the build process for everyone and may help the cn1 folks to switch to this port if they want. 

My suggestion is, we don't have many gaps in this port, actually I believe it is more feature complete than the official one, so if there is a gap in this port, there is probably the same gap in the official one.

About the official port, forget it, it will never reach a reasonable performance, it will never support truetype fonts, it is based on Silverlight and the rendering engine is hackish, leave the wounded behind.

**Comment by codenameone** [comment]
If you are working on porting the new VM that's an interesting direction, another one we are looking at right now is ikvm.net. 

Back in the day we couldn't use it because it didn't work on Windows Phone but it looks like it can be used for universal apps which is really what we need now... If you can get that to work we can switch the official port to this and fork it into the mainline. I'd love to use the newVM for both iOS and Windows Phone but the effort seems bigger than just switching to ikvm.

**Comment by FabricioCabeca** [comment]
Didn't know about ikvm.net, but I don't feel it would be easier.

Your work in the new VM for iOS seems harder to me than a possible Windows one, and you used the xmlvm concepts to create your own, I can't see why the same wouldn't work for Windows.

**Comment by codenameone** [comment]
ikvm.net should "just work" in theory without any VM code changes.

Originally when we wrote the VM we thought we'd take an approach similar to XMLVM on Windows Phone as well (translate to C#) but since Windows code can be written in C now that's also an option and most of the code can be reused as is.

Personally, I'm always in favor of the path of least resistance especially for windows which has been a pain for many years.

**Comment by sidiabale** [comment]
Hi,

Thanks for the response. If you can create a setup guide that would really
help.
